name: waste_management_and_recycle_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  flutter_signin_button: 2.0.0
  google_sign_in: 5.4.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  
  assets:
    - assets/background_Image.png
    - assets/Dustbin_set.png
    - assets/garbage_truck.png
    - assets/recycle.png
    - assets/transportation.png
    - assets/hazardous.png
    - assets/cleaner.png
    - assets/solid_waste.png
    - assets/organic_waste.png
    - assets/medical_waste.png
    - assets/eWaste.png
    - assets/plastic_waste.png
    - assets/Garbage.png
    - assets/profile_pic.png

  uses-material-design: true
